# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 21:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('type', models.SmallIntegerField(choices=[(1, b'Android'), (2, b'iOS')])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('active', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('sent',
                 models.SmallIntegerField(choices=[(0, 'Not Sent'), (2, 'In Progress'), (1, 'Sent')], default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_started', models.DateTimeField(null=True)),
                ('date_finished', models.DateTimeField(null=True)),
                ('filter_type', models.SmallIntegerField(blank=True, default=0)),
                ('filter_user', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
